### ISSUE TITLE
Clash with `rollup-plugin-typescript2`?

### ISSUE THREAD

**Issue by lazarljubenovic** [vladshcherbin/rollup-plugin-copy#16]
I created a barebones project with Typescript.

<details>
<summary> tsconfig.json </summary>

```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "esnext",
    "rootDir": "./src",
    "strict": true,
     "esModuleInterop": true
  }
}
```

</details>

<details>
<summary> package.json </summary>

```json
  "devDependencies": {
    "rollup": "^1.9.3",
    "rollup-plugin-copy": "^1.0.0",
    "rollup-plugin-typescript2": "^0.20.1",
    "typescript": "^3.4.3"
  }
```

</details>

With `src/index.html`  and `src/index.ts` present, I am getting the following error.

```text
[!] (rpt2 plugin) Error: Unknown object type "asyncfunction"
src/index.ts
Error: Unknown object type "asyncfunction"
    at Object._object (/home/lazar/basketball/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23691:17)
    at Object._function (/home/lazar/basketball/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23792:14)
    at Object.dispatch (/home/lazar/basketball/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23658:30)
    at /home/lazar/basketball/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23719:18
    at Array.forEach (<anonymous>)
    at Object._object (/home/lazar/basketball/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23715:21)
    at Object.dispatch (/home/lazar/basketball/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23658:30)
    at /home/lazar/basketball/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23733:23
    at Array.forEach (<anonymous>)
    at Object._array (/home/lazar/basketball/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23732:20)

1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Here's the config.

```js
import typescript from 'rollup-plugin-typescript2'
import copy from 'rollup-plugin-copy'

export default {
  input: 'src/index.ts',
  output: {
    file: 'dist/bundle.js',
    format: 'iife',
  },
  plugins: [
    copy({
      targets: [
        'src/index.html',
      ],
      outputFolder: 'dist',
    }),
    typescript({
      typescript: require('typescript'),
    }),
  ]
}
```

Commenting out any of the plugins make it work properly. This error was mentioned in https://github.com/ezolenko/rollup-plugin-typescript2/issues/105, but the rationale given seems irrelevant to this issue.

**Comment by vladshcherbin** [comment]
So, the issue is with `rollup-plugin-typescript2` plugin, the linked issue is exactly what it is.

In the docs, there is a [Compatibility / plugins using async/await](https://github.com/ezolenko/rollup-plugin-typescript2#plugins-using-asyncawait) section which points to using `objectHashIgnoreUnknownHack` option to fix this. The linked issue was also resolved this.

So, the solution is to try this option. Not sure I can fix this somehow in `rollup-plugin-copy`.

**Comment by vladshcherbin** [comment]
@lazarljubenovic I tried it and it actually works:

```js
typescript({
  typescript: require('typescript'),
  objectHashIgnoreUnknownHack: true,
}),
```

<details>
 <summary>Full config</summary>
 
```js
import typescript from 'rollup-plugin-typescript2'
import copy from 'rollup-plugin-copy'

export default {
  input: 'src/index.ts',
  output: {
    file: 'dist/bundle.js',
    name: 'myLibrary',
    format: 'iife',
  },
  plugins: [
    copy({
      targets: [
        'src/index.html',
      ],
      outputFolder: 'dist',
    }),
    typescript({
      typescript: require('typescript'),
      objectHashIgnoreUnknownHack: true,
    }),
  ]
}
```

</details>

Change this in your config and it should work too 😉

**Comment by lazarljubenovic** [comment]
I skimmed too quickly, I thought it was about `async` in _code_, not plugins. Sorry and thanks :sweat_smile:

**Comment by tonysamperi** [comment]
> @lazarljubenovic I tried it and it actually works:
> 
> ```js
> typescript({
>   typescript: require('typescript'),
>   objectHashIgnoreUnknownHack: true,
> }),
> ```
> 
> Full config
> Change this in your config and it should work too 😉

Thanks, it worked. Very wierd we need to do this, though.
